// Generated by dts-bundle-generator v8.1.2

export declare const IndexedRedis: <T>(dbName: string) => {
	setEx: <K extends keyof T>(key: K, expireSecond: number, obj: T[K]) => Promise<T[K]>;
	set: <K_1 extends keyof T>(key: K_1, obj: T[K_1]) => Promise<T[K_1]>;
	get: <K_2 extends keyof T>(key: K_2) => Promise<T[K_2] | undefined>;
	getAll: () => Promise<Partial<T>>;
	assign: <K_3 extends keyof T>(key: keyof T, obj: T[K_3]) => Promise<T[keyof T]>;
	remove: <K_4 extends keyof T>(key: K_4) => Promise<T[K_4] | undefined>;
	clearExpiredItems: (force?: boolean) => Promise<Partial<T> | undefined>;
};

export {};
